/*==============================================================*/
/* DBMS name:      ORACLE Version 10gR2                         */
/* Created on:     1/11/2023 7:55:40 p. m.                      */
/*==============================================================*/


DROP SEQUENCE CLIENTE_SEQ;

DROP SEQUENCE CUENTA_LOGS_SEQ;

DROP SEQUENCE CUENTA_SEQ;

DROP SEQUENCE TELEFONOS_SEQ;

CREATE SEQUENCE CLIENTE_SEQ
INCREMENT BY 1
START WITH 0
 NOMAXVALUE
 MINVALUE 0
NOCYCLE
 NOCACHE
ORDER;

CREATE SEQUENCE CUENTA_LOGS_SEQ
INCREMENT BY 1
START WITH 0
 NOMAXVALUE
 MINVALUE 0
NOCYCLE
 NOCACHE
ORDER;

CREATE SEQUENCE CUENTA_SEQ
INCREMENT BY 1
START WITH 0
 NOMAXVALUE
 MINVALUE 0
NOCYCLE
 NOCACHE
ORDER;

CREATE SEQUENCE TELEFONOS_SEQ
INCREMENT BY 1
START WITH 0
 NOMAXVALUE
 MINVALUE 0
 NOCACHE
ORDER;

