INSERT INTO BANCO.TIPO_TELEFONO (ID_TIPO_TELEFONO, NOMBRE) VALUES('FJ', 'Telefono Fijo');
INSERT INTO BANCO.TIPO_TELEFONO (ID_TIPO_TELEFONO, NOMBRE) VALUES('MV', 'Celular');
INSERT INTO BANCO.TIPO_TELEFONO (ID_TIPO_TELEFONO, NOMBRE) VALUES('ST', 'Telefono Satelital');