INSERT INTO TIPO_CLIENTE (ID, NOMBRE) VALUES ('RC', 'PASAPORTE');

INSERT INTO TIPO_CLIENTE (ID, NOMBRE) VALUES ('TI', 'PERMISO TEMPORAL');

INSERT INTO TIPO_CLIENTE (ID, NOMBRE) VALUES ('CC', 'REGISTRO NACIMIENTO');

INSERT INTO TIPO_CLIENTE (ID, NOMBRE) VALUES ('PS', 'REGISTRO CIVIL');

INSERT INTO TIPO_CLIENTE (ID, NOMBRE) VALUES ('PT', 'TARJETA IDENTIDAD');

INSERT INTO TIPO_CLIENTE (ID, NOMBRE) VALUES ('RN', 'CEDULA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'EMMA', 'TOVAR');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ALANNA', 'GAVIRIA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'VIOLETA, VIOLETTA', 'PALACIO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'EMILY', 'URIBE');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'ANTONIA', 'GUEVARA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'MARíA PAZ', 'ARBOLEDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'DULCE MARíA', 'MIRANDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'HELENA', 'MARQUEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'LUCíA', 'CIFUENTES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'SARA', 'MEZA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'VALERIA', 'SEPULVEDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MARíA CELESTE', 'RUEDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MARIáNGEL', 'FUENTES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'MíA', 'BENITEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ELENA', 'MENESES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'ABIGAíL', 'VELASCO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'SAMARA', 'LOAIZA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MARíA VICTORIA', 'ESTRADA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'ALICIA', 'NUñEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'VALENTINA', 'AGUILAR');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MARíA ANTONIA', 'AYALA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'PAULINA', 'SOLANO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'JULIANA', 'MONSALVE');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'SARA SOFíA', 'BOLAñOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'HANNAH', 'ARENAS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ELIZABETH', 'CABRERA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ZOE', 'GALINDO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ARIANA', 'BECERRA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'OLIVIA', 'FONSECA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MARíA PAULA', 'PERDOMO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ADHARA', 'CASTELLANOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'MACARENA', 'BETANCUR');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'RENATA', 'BOHORQUEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MANUELA', 'CAMPO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'VALERY', 'SALCEDO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'AMALIA', 'ZUñIGA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'LUNA', 'LUNA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'MIRANDA', 'GALEANO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'ABBY', 'CARMONA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ALAIA', 'PULIDO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ALMA', 'CARO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ANA LUCíA', 'MELO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ANA VICTORIA', 'GONZALES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'IVANNA', 'BRAVO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'JUANITA', 'JAIMES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'MILAGROS', 'ROSERO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ALEJANDRA', 'PRIETO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MíA ISABELLA', 'FIGUEROA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'SUSANA', 'QUIñONES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'VERóNICA', 'SANABRIA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ANA MARíA', 'NIETO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'CAMILA', 'MURCIA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MONTSERRAT', 'BAUTISTA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'AITANA', 'SALAS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'AURORA', 'CANTILLO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'AVRIL', 'PINTO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'LETICIA', 'VERA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'SALMA', 'ESPITIA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'THALIANA', 'MONTAñO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ANTONELLA', 'ZULUAGA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ISABELLA', 'CEBALLOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'LUCIANA', 'ALVARADO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'CELESTE', 'ALARCON');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'VICTORIA', 'RIASCOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'GABRIELA', 'CHAVEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'MARIANA', 'ROA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'JULIETA', 'CASTRILLON');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'SALOMé', 'SERRANO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'GUADALUPE', 'TRIANA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'AMELIA', 'LARA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'SAMANTHA', 'BERRIO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MARTINA', 'PARDO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'SOFíA', 'RENDON');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'EMILIA', 'NARANJO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MARíA JOSé', 'RIVAS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'EMMA', 'MONTENEGRO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ALANNA', 'GARCES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'VIOLETA, VIOLETTA', 'SALGADO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'EMILY', 'JULIO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ANTONIA', 'OVIEDO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'MARíA PAZ', 'CABALLERO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'DULCE MARíA', 'ANDRADE');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'HELENA', 'FAJARDO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'LUCíA', 'MALDONADO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'SARA', 'BARBOSA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'VALERIA', 'VILLEGAS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MARíA CELESTE', 'VILLAMIZAR');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MARIáNGEL', 'BARRETO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MíA', 'YEPES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ELENA', 'POSADA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ABIGAíL', 'URREGO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'SAMARA', 'OSPINO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'MARíA VICTORIA', 'CUELLAR');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ALICIA', 'PABON');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'VALENTINA', 'QUIROGA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MARíA ANTONIA', 'DOMINGUEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'PAULINA', 'BOLIVAR');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'JULIANA', 'TABORDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'SARA SOFíA', 'RICO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'HANNAH', 'SANTOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ELIZABETH', 'ARROYO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'ZOE', 'LEAL');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ARIANA', 'VALLEJO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'OLIVIA', 'BALLESTEROS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MARíA PAULA', 'RANGEL');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ADHARA', 'GAMBOA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MACARENA', 'VELANDIA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'RENATA', 'CHACON');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MANUELA', 'BURBANO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'VALERY', 'BUSTOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'AMALIA', 'ACUñA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'LUNA', 'RUBIO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MIRANDA', 'PEDRAZA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ABBY', 'SEGURA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ALAIA', 'OLAYA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ALMA', 'MONROY');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ANA LUCíA', 'BUSTAMANTE');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ANA VICTORIA', 'QUIROZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'IVANNA', 'IBARRA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'JUANITA', 'SAAVEDRA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MILAGROS', 'ALFONSO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ALEJANDRA', 'MENA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MíA ISABELLA', 'CERON');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'SUSANA', 'OBANDO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'VERóNICA', 'PRADA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ANA MARíA', 'ERAZO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'CAMILA', 'CARREñO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MONTSERRAT', 'BEJARANO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'AITANA', 'CHAPARRO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'AURORA', 'HINCAPIE');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'AVRIL', 'CACERES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'LETICIA', 'AVENDAñO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'SALMA', 'PEREA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'THALIANA', 'VALDERRAMA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ANTONELLA', 'ARTEAGA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'ISABELLA', 'TABARES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'LUCIANA', 'TAMAYO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'CELESTE', 'SALAMANCA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'VICTORIA', 'CARDOZO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'GABRIELA', 'PAZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MARIANA', 'MONTERO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'JULIETA', 'ORJUELA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'SALOMé', 'ANAYA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'GUADALUPE', 'VILLAMIL');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'AMELIA', 'BARRAGAN');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'SAMANTHA', 'PUENTES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'MARTINA', 'ALDANA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'SOFíA', 'RENTERIA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'EMILIA', 'BELLO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MARíA JOSé', 'BURGOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'EMMA', 'ANGARITA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ALANNA', 'RIAñO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'VIOLETA, VIOLETTA', 'GRAJALES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'EMILY', 'BASTIDAS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ANTONIA', 'CORREDOR');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MARíA PAZ', 'BETANCOURT');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'DULCE MARíA', 'ARISTIZABAL');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'HELENA', 'QUINTANA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'LUCíA', 'GRANADOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'SARA', 'MONCADA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'VALERIA', 'CADENA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'MARíA CELESTE', 'CUERVO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MARIáNGEL', 'MARULANDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MíA', 'RENGIFO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ELENA', 'ROCHA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ABIGAíL', 'PINILLA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'SAMARA', 'PANTOJA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'MARíA VICTORIA', 'CASTIBLANCO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ALICIA', 'CLAVIJO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'VALENTINA', 'PIEDRAHITA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'MARíA ANTONIA', 'PATERNINA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PT', 'PAULINA', 'HOLGUIN');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'JULIANA', 'MANRIQUE');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'SARA SOFíA', 'PUERTA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'HANNAH', 'CUBILLOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ELIZABETH', 'PULGARIN');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ZOE', 'TELLEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ARIANA', 'SANTANA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'OLIVIA', 'ROZO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MARíA PAULA', 'VIDAL');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ADHARA', 'OJEDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MACARENA', 'DURANGO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'RENATA', 'PUSHAINA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'MANUELA', 'CHAMORRO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'VALERY', 'CELIS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'AMALIA', 'SAENZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'LUNA', 'MAHECHA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MIRANDA', 'BARON');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'ABBY', 'VILLADA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ALAIA', 'ANGEL');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'ALMA', 'POVEDA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ANA LUCíA', 'GRISALES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('PS', 'ANA VICTORIA', 'PERALTA');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'IVANNA', 'CAMPOS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'JUANITA', 'BAQUERO');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'MILAGROS', 'CERVANTES');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('CC', 'ALEJANDRA', 'SALINAS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('TI', 'MíA ISABELLA', 'PORRAS');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'SUSANA', 'RODRIGUEZ');

INSERT INTO CLIENTE (TIPO_CLIENTE_ID, NOMBRE, APELLIDOS) VALUES ('RC', 'VERóNICA', 'MARTINEZ');

